baseURL = 'https://analogriktning.kallmoraberget.com/'
languageCode = 'en-us'
title = 'analog riktning'
theme = 'hugo-theme-re-terminal-main'
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  favicon = "/favicon.png"
    [languages]
  [languages.en.params]
    title = "analog-riktning"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "analog // riktning"
      logoHomeLink = "/"
      [params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "erikalvner"
  site = "erikalvner"

#[languages.en.menu]
 # [[languages.en.menu.main]]
 #   identifier = "om"
 #   name = "om"
 #   url = "/om"
#  [[languages.en.menu.main]]
 #   identifier = "varfor"
 #   name = "varför?"
 #   url = "/varfor"
